version: '3'

services:
  mondrian:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./mondrian-config:/usr/local/tomcat/webapps/mondrian/WEB-INF/classes
      - ./data:/opt/mondrian/data
    depends_on:
      - mysql
    environment:
      - JAVA_OPTS=-Xmx2048m -Dmondrian.rolap.generate.formatted.sql=true
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=foodmart
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql-data:
